// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Yami_SkipTitle","status":false,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"RelativeTouchPad","status":true,"description":"もどきぷにコンプラグイン","parameters":{"タッチ有効領域":"0,0,640,960","パッド画像ファイル":"","アロー画像ファイル":"","パッド画像不透明度":"255"}},
{"name":"ScreenResolution","status":true,"description":"ゲームスクリーンの解像度を好きなように変更することができます","parameters":{"Screen Width":"640","Screen Height":"960"}},
{"name":"EventReSpawn","status":true,"description":"イベント動的生成プラグイン","parameters":{}},
{"name":"TemplateEvent","status":true,"description":"テンプレートイベントプラグイン","parameters":{"テンプレートマップID":"1","イベントIDを維持":"OFF","グラフィック置換":"OFF"}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"OFF","ピクチャ番号の変数番号":"0","ポインタX座標の変数番号":"0","ポインタY座標の変数番号":"0","タッチ操作抑制":"OFF"}},
{"name":"SAN_AnalogMove","status":true,"description":"アナログムーブ ver1.40\r\n1ピクセル単位の移動 アナログスティック・タッチパッド対応","parameters":{"Valid":"ON","Player":"ON","PreventThrough":"OFF"}},
{"name":"TDDP_ManageDashing","status":true,"description":"ゲーム内でのダッシュモードの利用が可能になります。","parameters":{"Disable Auto-dash":"false","Disable Dashing":"true","Remove Dash Option":"false"}},
{"name":"SyncVariable","status":true,"description":"ユーザ間の変数同期プラグイン","parameters":{"ユーザID":"susumago0077","同期開始変数番号":"21","同期終了変数番号":"60","同期開始スイッチ番号":"21","同期終了スイッチ番号":"60","認証ファイル形式":"OFF"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"AdjustPictureGraphical","status":false,"description":"ピクチャのグラフィカルな位置調整プラグイン","parameters":{}}
];
